# Generated by Django 4.2.7 on 2024-02-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'members',
            },
        ),
    ]
